version: '3'

services:
  backend:
    image: your-backend-image-name
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/dbname
    depends_on:
      - db

  frontend:
    image: your-frontend-image-name
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
